# Site settings
title: Claiomh Solais Consulting
email: jcoffie@solaisconsulting.com
description: > # Claiomh Solais Consulting, LLC .....  (This data shows up
  in the description of the site)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://solaisconsulting.com" # the base hostname & protocol for your site
twitter_username: SolaisConsult
github_username:  SolaisConsulting

# Build settings
markdown: kramdown
